version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: cpc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cpc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cpc_redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
