# Generated by Django 4.2.9 on 2024-02-03 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reminder",
        ),
    ]
