# Generated by Django 4.2.9 on 2024-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_productreminder_shopify_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreminder",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
