# Generated by Django 4.2.9 on 2024-02-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_productreminder_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreminder",
            name="threshold",
            field=models.IntegerField(
                default=0,
                help_text="Threshold for the product, if below a reminder will be sent.",
            ),
        ),
    ]
