# Generated by Django 5.0.6 on 2024-05-16 23:00

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_productreminder_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "shopify_id",
                    models.BigIntegerField(help_text="Shopify ID of the collection"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug of the collection for internal tracking only",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
