# Generated by Django 5.0.6 on 2024-05-16 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_collectionreminder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductReminder",
        ),
    ]
